spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms-email?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: ******
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    username: ************@gmail.com
    password: ****************
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  rabbitmq:
    addresses: *******************
    queue: ms.email

logging:
  level:
    com:
      ms:
        email: TRACE
#    root: DEBUG

server:
  port: 8081